[2025-03-26 20:20:41] [INFO] [conftest.py:32] - 创建API客户端实例
[2025-03-26 20:20:41] [INFO] [api_client.py:155] - 发送 POST 请求: http://localhost:8081/user/login, json: {'number': '001', 'username': 'admin', 'password': 'Lx123456'}
[2025-03-26 20:20:41] [ERROR] [api_client.py:175] - 请求异常: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104c12e20>: Failed to establish a new connection: [Errno 61] Connection refused'))
[2025-03-26 20:20:41] [ERROR] [api_client.py:52] - 登录失败: None
